# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@8.3.18
  - npm install
  - ng build --base-href "https://medicaldataworks.gitlab.io/diolkos/server-ui/"
  artifacts:
    paths:
    - public
  only:
  - master
  - pages

